apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tytsqmwm6-python-ci
  namespace: rhtap-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/tytsqmwm6-python/overlays/ci
    repoURL: https://github.com/tnevrlka-rhtap/tytsqmwm6-python-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-ci
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: rhtap-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
